meta:
  environment: ~
  instances: (( merge ))
  token: (( merge ))

update:
  canaries: 0
  max_in_flight: (( meta.instances ))
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: buildkite_agent_z1
    templates:
      - name: buildkite_agent
        release: buildkite-agent
    instances: (( meta.instances ))
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties:
  buildkite_agent:
    token: (( meta.token ))
